# Generated by Django 3.2.18 on 2023-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alertasNovos',
            field=models.IntegerField(default=0, verbose_name='alertas não lidos'),
        ),
    ]
