# Generated by Django 3.2.18 on 2023-05-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
