# Generated by Django 4.2 on 2023-05-31 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0004_estado_os_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OS.estado'),
        ),
    ]
