# Generated by Django 4.2 on 2023-06-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0005_alter_os_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='os',
            options={'verbose_name': 'OS', 'verbose_name_plural': 'OS'},
        ),
        migrations.AlterField(
            model_name='estado',
            name='color',
            field=models.CharField(default='color:#FF0000;', max_length=50, verbose_name='cor'),
        ),
    ]
