# Generated by Django 4.2 on 2023-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0006_alter_estado_options_alter_os_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='colorHTML',
            field=models.CharField(default='color:#FF0000;', max_length=50, verbose_name='cor html'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='color',
            field=models.CharField(default='#FF0000', max_length=8, verbose_name='cor'),
        ),
    ]
